- src/components/GTabs/GTabs.vue
Why ?
toLocaleUpperCase blocks user to use their own naming style on labels.
For example,
A user needs to use title case naming, but he/she can't do this, because of toLocaleUppercase
> Remove toLocaleUpperCase from label

- src/components/GBadge/GBadge.spec.ts
- src/components/GBadge/GBadge.vue
- src/components/GBadge/__snapshots__/GBadge.spec.ts.snap
Why?
Updated v-if, v-else conditions for performance.
Updated g-border-color class usage to style based var usage. Because, this component should not rely on global classes which should be imported in main app. This component should work without importing that utility classes. It takes too much space such as 20-30kb to store all the colors with classes.
Separation of Concerns
Due this princible each component should be independent. If you would like to follow this princible i will going to update each component to make it independent.
> GBadge, better performance, class independence 

- src/components/GButton/GButton.vue
GButton gradient variant has a bug on Safari browser.
I fixed it. 
Before:
After:
> Fix Safari gradient button bug

- .storybook/main.js
- .storybook/preview.js
- src/components/gr-button/gr-button.stories.mdx
This is a workaround for the issue that I asked about here: https://stackoverflow.com/questions/71999979/storybook-web-component-code-examples-extra-comment-tags
I debugged the issue and noticed some points: Apparently empty string value for boolean attributes with a truthy value is expected in lit-html ([Check test file](https://github.com/lit/lit/blob/main/packages/lit-html/src/test/lit-html_test.ts#L1131)) Since storybook just [uses ](https://github.com/storybookjs/storybook/blob/next/app/web-components/src/client/docs/sourceDecorator.ts#L46)render[ method](https://github.com/storybookjs/storybook/blob/next/app/web-components/src/client/docs/sourceDecorator.ts#L46) of lit and reads innerHTML of the element to show code sample, this behavior is expected. But I think that doesn’t make …
> fix(storybook): fix for code sample issues

- .npmrc
`package-lock.json` format is changed with Node v16. And it's not compatible with Node v14. We put engine requirement in our package.json file as `>=16` but this only shows a warning and many people don't even notice it. Then we are having contributions from the dev env. both node v14 and v16. That causes a full re-write of `package-lock.json` files in our commits.
This PR prevents this by adding [`engine-strict`](https://docs.npmjs.com/cli/v7/using-npm/config#engine-strict) rule to our `.npmrc` file. After this if you make `npm install` in an environment that older node version than v16, you see an error like below:
```bash
➜  baklava git:(prevent-old-node-versions) ✗ npm i
npm ERR! code ENOTSUP
npm ERR! notsup Unsupported engine for @trendyol/baklava@0.0.0-dev: wanted: {"node":">=16"} …
```
> chore: prevent using old node versions

- .github/workflows/publish-chromatic.yml
- .github/workflows/publish-storybook.yml
- .github/workflows/verify.yml
While I was working on implementing sonarqube, I noticed that `setup-node` action has [caching capability](https://github.com/actions/setup-node#caching-global-packages-data). Since we already have #124 I just wanted to try this simple change.
Also I noticed playwright-action [encourages to use playwright-cli](https://github.com/microsoft/playwright-github-action#%EF%B8%8F-you-dont-need-this-github-action-%EF%B8%8F) instead of their action. I followed their suggestion here too.
> ci: npm cache and remove playwright action

- package-lock.json
- package.json
- src/components/badge/bl-badge.test.ts
- src/components/button/bl-button.test.ts
- src/components/input/bl-input.test.ts
- web-test-runner.config.mjs
No more need to require mocking fetch method because of using `bl-icon` component
inside others.
Closes #147
> test: bl-icon is mocked for tests other than its own test

- src/components/tooltip/bl-tooltip.css
As a result of our conversation with @buseselvi, due to the content doesn't fit in the tooltip, the max-width has been changed.
> fix(tooltip): change max-width for tooltip

- src/components/badge/bl-badge.css
- src/components/badge/bl-badge.stories.mdx
As we discussed in #164, it was not possible to set badge CSS variables from upper levels of dom tree because default values set in `:host` selector. This was causing difficulties to style badge in `tab` component, because we use badge inside tab component's shadow dom and it's not possible to query badge inside tab in CSS. This makes CSS variables of badge component like a theme variables, so user can set those variables in any scope (badge component level, parent component level or document level).
> fix(badge): css variables used as privately

- docs/using-baklava-in-react.stories.mdx
I think it would be useful for React users to see directly from the doc how to style components.
> docs: add Styling Components section to react doc

- src/components/button/bl-button.css
- src/components/button/bl-button.stories.mdx
- src/components/button/bl-button.test.ts
- src/components/button/bl-button.ts
- src/components/tab-group/tab/bl-tab.ts
- src/components/tooltip/bl-tooltip.stories.mdx
**This is a BREAKING CHANGE**
Currently we use boolean attributes for button variants (`primary`, `secondary`, `success`, `danger`) and types (`contained`, `outline`, `text`). In the beginning we thought this is easier to write but currently I see that this is conflicting with the approach how we use boolean attributes in other components and how we really should use them. Boolean attributes should not rely on other attributes. But now we are technically allowed to write `<bl-button primary secondary>` and in this case result relies on our CSS specifity. And this type of writing does give the feeling that it's possible.
I think we need to fix this as soon as possible to not make confusion for new comers.
This PR converts boolean variants to a more standart `variant` attribute with a …
> fix(button)!: button attributes refactored

- src/components/tooltip/bl-tooltip.css
- src/components/tooltip/bl-tooltip.stories.mdx
- src/components/tooltip/bl-tooltip.ts
We were using `absolute` position by default for the tooltip positioning. But when the parent element of the tooltip has `overflow:hidden` style the tooltip isn't shown correctly. For these cases, we provided to set the tooltip position as `fixed`.  But `absolute` position causes the positioning bug in `Tab` component like that issue https://github.com/Trendyol/baklava/issues/197
We discussed before with @muratcorlu and we decided to use only `fixed` position.
In addition, I fixed CSS properties according to our decision in discussion https://github.com/Trendyol/baklava/discussions/164
Closes https://github.com/Trendyol/baklava/issues/197
> fix(tooltip): tooltip positioning bug fix

- src/components/badge/bl-badge.stories.mdx
- src/components/button/bl-button.stories.mdx
- src/components/icon/bl-icon.stories.mdx
- src/components/input/bl-input.stories.mdx
- src/components/progress-indicator/bl-progress-indicator.stories.mdx
- src/components/tab-group/bl-tab-group.stories.mdx
- src/components/tab-group/tab-panel/bl-tab-panel.stories.mdx
- src/components/tab-group/tab/bl-tab.stories.mdx
- src/components/tooltip/bl-tooltip.stories.mdx
Added a note to warn user that using inline styling examples are only for **demo purposes** at storybook components.
We will add admonitions to make this more catchy.
Any advice would be highly appreciated.
**Note**: We think that, we should update our contribution gudeline for more information for new comers (for example: initial setup, styling rules, development rules etc) and add documentation gudeline to our documentation. It will be specified in another issue. There are some related issues in our issue board, I will refer them after organising the problems.
Closes #196
> docs: add note for using inline styling at storybook components

- src/components/tooltip/bl-tooltip.css
- src/components/tooltip/bl-tooltip.ts
I noticed some missing parts with #202. I converted CSS variables to private to not being able to set outside. And also there were small forgotten style and docs.
> fix(tooltip): convert tooltip css variables to private

- README.md
NPM and jsDelivr badges were linked to SVG images. Linked them to related URLs.
> docs: badge links are fixed

- scripts/build.js
There is a builtin option in our css plugin named [uglifycss](https://www.npmjs.com/package/uglifycss). So, we can just add `uglify: true` option to minify our css. Output seems good and I didn't want to add another step/plugin to minify the css. I believe, this'll work for us.
Closes #175
> feat: minify css

- src/components/input/bl-input.ts
Changes on `value` attribute of `bl-input` was not updating native input's value inside the component. Instead of setting value of the native input by attribute, I changed by setting the "property" of the native input.
Fixes #218
> fix(input): listen value changes in native input

- commitlint.config.js
- src/components/select/bl-select.css
- src/components/select/bl-select.test.ts
- src/components/select/bl-select.ts
When we open the popup of select, it changes the arrow icon from down to up. But since we are lazily loading icons, loading of the up icon can take some time regarding the network speed of the client. That timing causes taking randomly different screenshots on our Chromatic snapshots testing. As a result of this, our `next` branch can go to UI review status and block some PRs like #253.
I fixed this by including both icons in the dom by default and showing/hiding them with CSS. I think this is also better for even end users because with some lousy network connections, in current behavior, a user can see the delay of seeing icon change when they open select for the first time.
> fix(select): fix delay of arrow icon change on opening popup

- src/components/tooltip/bl-tooltip.css
The tooltip shrink without off max-content width. You can see from [Stackblitz](https://stackblitz.com/edit/vitejs-vite-pdvgcp?file=src/App.css).
Steps to reproduce:
1. Create a fixed size div with `transform: translateY(1px);` style.
2. Add tooltip inside.
OLD:
NEW:
> fix(tooltip): use max-content width for tooltip content

- src/components/select/bl-select.ts
- As mentioned in this [issue#252](https://github.com/Trendyol/baklava/issues/252) there is a bug in `_closeOutsideHandler` function. 
- I realized another bug when `multiple = false`. It is not appearing in the selected state when an option is selected.
- Also, event listeners moved into `open` and `close` functions
Fixes #252
> fix(select): popover and selected issues

- src/components/pagination/bl-pagination.ts
While using the pagination component in my project, I noticed that the pagination component does not refresh when the total count of items changes.
We get the total count of items from the backend and the pagination was not refreshing when the response came as we did not track this `totalItems` property. This pr fixes this problem.
> fix(pagination): totalItems change control added

- docs/design-system/colors.stories.mdx
- src/components/button/bl-button.css
- src/components/checkbox/bl-checkbox.css
- src/components/tooltip/bl-tooltip.css
- src/themes/default.css
Featured and alternative hover colors were wrong, they were fixed and added new content color because we were using the `--bl-color-primary-background` for white content text but it doesn't fit our theme rules as semantically.
> fix: featured and alternative colors fixed and new colors added

- .vscode/extensions.json
This extension has been deprecated in favor of the official MDX extension.
> chore: deprecated extension removed

- README.md
- docs/using-baklava-in-react.stories.mdx
- docs/using-baklava-in-vue.stories.mdx
- package.json
- scripts/generate-react-exports.js
- src/components/button/bl-button.stories.mdx
Includes:
* Generating the types with tsc,
* Fixing the generate-react-exports.js by including all the component type imports and hooking up the component with its types to the "createComponent" function provided by @lit-labs/react
* Updating the docs for the beta version.
Closes #272.
> fix: generate type declarations for build

- docs/using-baklava-in-react.stories.mdx
We noticed that using different versions on CDN and NPM can cause some compatibility issues between React wrapper and actual Web Component #280 This change adds a warning to point on that issue
> docs: warning added about npm and cdn versions

- docs/using-baklava-in-vue.stories.mdx
While using baklava in vue projects we have to add eslint configuration for kebab-case. I added this configuration in vue documentation.
> docs: add eslint info to the vue doc

- src/components/pagination/bl-pagination.css
- src/components/pagination/bl-pagination.stories.mdx
- src/components/pagination/bl-pagination.test.ts
- src/components/pagination/bl-pagination.ts
Improvements:
* The "itemsPerPageOptions" array property is added,
* Default items-per-page is changed from 100 to 10,
* The "option-text" attribute is removed since the itemsPerPageOptions property includes texts and values,
The usage:
```
<bl-pagination current-page="1" total-items="1500" 
</bl-pagination>
pagination.itemsPerPageOptions = [
{
text: '100 Items',
value: 100,
},
{
text: '250 Items',
value: 250,
},
{
text: '500 Items',
value: 500,
},
{
text: '1000 Items',
value: 1000,
},
]
```
* Lastly, the component had no responsivity before, so little style changes are added.
This part can be improved if @buseselvi has any feedbacks.
Closes #284.
> fix: pagination items per page options

- src/components/pagination/bl-pagination.test.ts
- src/components/pagination/bl-pagination.ts
We should send to `itemsPerPage` value with `bl-change` event when select any item in `items per page` select  for fetching new list from api.
> fix(pagination): add item per page value bl-change event

- src/components/pagination/bl-pagination.ts
* Currently, pagination component throws bl-change event on first render cycle when no attribute (current-page, total-items and items-per-page) has changed.
* When the total-items changes on api calls, pagination re-renders and re-throw the event. This causes fetching duplicate data.
This pr fixes this issue by listening only the current-page and items-per-page changes.
> fix(pagination): throw events only on page & total-items changes

- scripts/generate-react-exports.js
If a component file has multiple export statements, our react generator script fails to read component metadata, because it was checking the first export of the file. That was causing problem since radio component exports some other variables too.
Fixed it.
> fix: react wrapper for component files with multiple exports

- src/components/checkbox-group/checkbox/bl-checkbox.css
- src/components/checkbox-group/checkbox/bl-checkbox.stories.mdx
- src/components/select/bl-select.css
- src/components/select/bl-select.stories.mdx
This fixes several visual issues about checkbox and select components that is reported in #353 and #352 
* Checkbox checkmark background color
* Checkbox checkmark deformation with limited space
* Checkbox label with long text and multiple lines
* Select component long placeholder and labels
I tried to add extra stories to our storybook to cover those situations in our visual tests.
Fixes #353 
Fixes #352
> fix(select): visual fixes over long texts

- .storybook/preview-head.html
- docs/customizing-baklava-theme.stories.mdx
- docs/design-system/typography.stories.mdx
- src/components/alert/bl-alert.css
- src/components/alert/bl-alert.ts
- src/components/checkbox-group/checkbox/bl-checkbox.css
- src/themes/default.css
Some visual updates on our Alert component regarding to our updated [Figma document](https://www.figma.com/file/RrcLH0mWpIUy4vwuTlDeKN/Baklava-Design-Guide?node-id=2815%3A14630&t=GYqRcNG6DYvgT0Nn-0).
I made some big changes here by setting line-heights for our typography rules -again-. This was needed to have consistent heights on alert component. I used some new set of css tokens in our default theme file. I added some documents about how to customise them.
Closes #318
> fix(alert): visual arrangements for alerts and font line-heights

- docs/requirements.stories.mdx
In this documentation, we want to guide baklava users how they improve their browser support and to specify baklava's browser support by default. Right now, we support **95%** of all browser versions by default.
Why we avoid by adding polyfills to the baklava? Because, there is no way to dynamically add polyfills in baklava that runs only when needed. We don't want to have a fat bundle.
During the work, we found out, there are some other options. Actually, these options that came our mind before, but needed so much effort that we didn't have at that time when we prioritized issues. 
We may add some additional configs and strategies to improve our default bundle, or create a bundle that supports legacy browsers. We will create regarding issues about that. 
Stay tuned!
Closes #304.
> docs: add requirements documentation

- src/components/input/bl-input.ts
We use `label` and `label-fixed` attributes in styles of component. So they should be reflected.
Fixes #378
> fix(input): reflection of attributes used in styles

- .storybook/assets/demo-iframe.html
- .storybook/main.js
- src/components/drawer/bl-drawer.css
- src/components/drawer/bl-drawer.stories.mdx
I added an internal demo page for using with Drawer component in storybook. This should prevent having failing snapshot tests on Chromatic because of failing urls.
Fixes #330
> test(storybook): iframe url provided for drawer demo

- src/components/select/bl-select.ts
Fixes, `labelFixed` property is unusable as a React attribute.
> fix(select): reflect label-fixed attribute

- README.md
- src/components/alert/bl-alert.stories.mdx
- src/components/badge/bl-badge.stories.mdx
- src/components/button/bl-button.stories.mdx
- src/components/checkbox-group/bl-checkbox-group.stories.mdx
- src/components/checkbox-group/checkbox/bl-checkbox.stories.mdx
- src/components/dialog/bl-dialog.stories.mdx
- src/components/drawer/bl-drawer.stories.mdx
- src/components/dropdown/bl-dropdown.stories.mdx
- src/components/dropdown/group/bl-dropdown-group.stories.mdx
- src/components/dropdown/item/bl-dropdown-item.stories.mdx
- src/components/icon/bl-icon.stories.mdx
- src/components/input/bl-input.stories.mdx
- src/components/pagination/bl-pagination.stories.mdx
- src/components/progress-indicator/bl-progress-indicator.stories.mdx
- src/components/radio-group/bl-radio-group.stories.mdx
- src/components/radio-group/radio/bl-radio.stories.mdx
- src/components/select/bl-select.stories.mdx
- src/components/select/option/bl-select-option.stories.mdx
- src/components/switch/bl-switch.stories.mdx
- src/components/tab-group/bl-tab-group.stories.mdx
- src/components/tab-group/tab-panel/bl-tab-panel.stories.mdx
- src/components/tab-group/tab/bl-tab.stories.mdx
- src/components/tooltip/bl-tooltip.stories.mdx
* Added ADR and Figma links to component storybook pages.
* Added some useful links to our Readme file to make them easy to discover.
* I grouped sub components in a single folder to simplify the component list in storybook (like tab, tab-panel, tab-group to tab)
> docs: adr and figma links have been added to component docs

- .storybook/preview.js
- src/components/icon/bl-icon.css
- src/components/input/bl-input.css
- src/components/input/bl-input.stories.mdx
- src/components/input/bl-input.test.ts
- src/components/input/bl-input.ts
- src/themes/default.css
This PR fixes various issues in input component
* Disabled style for input fixed
* Small size added
* Vertical alignments fixed
* Internal component structure refactored for creating extra flexibility for upcoming features (like #388), better reliability and maintainability
* A sizing issue in Safari for icon component fixed
* Handling of long labels those doesn't fit the input
* Caption font-size fixed (it's 10px in design but it was 12px in our default.css)
* Input padding was 1px off comparing to design
* Input padding was wrong on iPad, fixed
Fixes #387
Closes #374
> fix(input): disabled style and small size fixes

- src/components/textarea/bl-textarea.css
Unneeded top padding in textarea while using with fixed labels cleared.
Fixes #400
> fix(textarea): unneeded padding cleared

- src/components/button/bl-button.test.ts
- src/components/button/bl-button.ts
- src/components/input/bl-input.stories.mdx
- src/components/textarea/bl-textarea.stories.mdx
Now `<bl-button type="submit">Submit</bl-button>` submits wrapping form.
Fixes #285
> fix(button): submit type works

- commitlint.config.js
- scripts/generate-react-exports.js
@Enes5519 noticed a problem in their Cypress tests inside Electron, that fails while defining React wrappers. We are getting the reference of the custom element with `customElements.whenDefined(elem =>` and pass this `elem` reference to the `createComponent` method of Lit's react component generator. But somehow in Electron, this `elem` becomes `undefined`, but `customElements.get('bl-button')` returns the proper class reference.
While we are still investigating the reason, I just created this PR to be ready to change our approach, since result doesn't change on both ways.
> fix(react): fix custom element undefined error in electron

- src/components/input/bl-input.ts
- src/components/pagination/bl-pagination.test.ts
- src/components/pagination/bl-pagination.ts
- src/components/textarea/bl-textarea.ts
We realized that our input and textarea components don't listen to changes on value **property** to update their validation states. This PR solves this issue.
While solving the issue, some tests of the pagination component failed. Then I noticed some problems with how we fire and listen to `bl-change` events of pagination. So this PR also includes some refactor in the pagination component.
> fix(input): fix listening value property changes

- src/components/textarea/bl-textarea.test.ts
This PR fixes the test in Textarea component which was failing with timeout due to `sendKeys` with a long text.
> test(textarea): fix timeout test

- src/components/select/bl-select.test.ts
- src/components/select/bl-select.ts
We realized that while we have a multiple selection in select component with additional selection counter visible (button with content like +3), once we set `.value` property via js, this number doesn't refreshed. This PR fixes this issue.
> fix(select): fix additional selection number when value set empty

- scripts/build.js
- src/components/button/bl-button.ts
- src/components/dialog/bl-dialog.css
- src/components/dialog/bl-dialog.stories.mdx
- src/components/dialog/bl-dialog.ts
- src/components/input/bl-input.test.ts
- src/components/input/bl-input.ts
- src/components/select/bl-select.ts
- src/components/textarea/bl-textarea.css
- src/components/textarea/bl-textarea.test.ts
- src/components/textarea/bl-textarea.ts
- src/utilities/form-control.ts
This PR adds missing attributes defined in #405. (currently only for Input and Textarea)
Also added `autofocus` to `bl-button` to allow fixing #406 
Some remarks:
* `autofocus` doesn't work on non-native form elements on Firefox and Safari ([Source](https://caniuse.com/?search=autofocus)). So autofocus doesn't work on select component on those browsers. 
* `autocomplete` doesn't work on Select component. It needs a native form element.
Fixes #474 
Fixes #451 
Closes #406 by adding some examples in Dialog storybook document
> feat: new attributes for form fields

- src/components/dialog/bl-dialog.stories.mdx
Added 2 examples about show full-width (block) action buttons in Dialog.
Closes #461
> docs(dialog): examples with full-width actions added

- src/components/dropdown/bl-dropdown.css
- src/components/dropdown/bl-dropdown.test.ts
- src/components/dropdown/bl-dropdown.ts
- src/components/popover/bl-popover.ts
This PR implements using popover component inside dropdown component by replacing local implementation. To do that we needed to change `fit-size` behaviour of popover. If `fit-size` set, popover will have the minimum size of it's trigger element. If content will be larger, than popover will increase until it's max-width.
Fixes #480
> fix(popover): using min-width for fit-size

- src/components/switch/bl-switch.css
- src/components/switch/bl-switch.stories.mdx
- src/components/switch/bl-switch.ts
* add `--bl-switch-color-on` and `--bl-switch-color-off` variables for switch
* deprecate `--bl-switch-color` in favor of `--bl-switch-color-on`
Fixes #523
> feat(switch): implement off color variable on bl-switch

- src/components/dropdown/bl-dropdown.test.ts
- src/components/dropdown/item/bl-dropdown-item.ts
This pull request adds automatic closing of the dropdown menu when an action is selected in the popover. This improves the user experience by eliminating the need for users to manually close the menu.
Fixes https://github.com/Trendyol/baklava/issues/529
> fix(dropdown): close dropdown when an item is clicked

- .npmrc
- package-lock.json
- scripts/generate-react-exports.js
- src/components/icon/bl-icon.test.ts
- src/components/select/bl-select.ts
- src/components/switch/bl-switch.ts
This PR fixes missing types in React wrappers.
> fix: fix react wrapper types

- src/components/select/bl-select.test.ts
Recently unit tests was failing on some local environments on Webkit. It was about how we do keyboard navigation on select tests, this PR fixes it.
> test: fix failing keyboard nav tests in webkit

- src/components/dialog/bl-dialog.ts
When dialog opens and being closed by user with `Escape` key, event prevented to avoid exiting browser from fullscreen.
Fixes #542
> fix(dialog): prevent exiting browser fullscreen with dialog close

- src/components/select/option/bl-select-option.css
We noticed that we broke select item separator while we merge stuff. This fixes it.
> fix(select): separator is back

- .eslintrc.cjs
- package.json
- scripts/build.js
- scripts/generate-react-exports.js
This pull request adds the "type: module" field to the package.json file. This change is made to indicate that our component library uses ECMAScript (ES) modules syntax and is designed to be consumed as an ES module.
Motivation:
By adding "type: module", we explicitly inform the JavaScript runtime and developers that our library follows the ES modules standard. This helps in promoting interoperability and enables seamless integration with modern JavaScript environments that natively support ES modules.
Benefits:
1. Clearer intent: By explicitly stating that our library uses ES modules, it becomes easier for developers to understand and utilize the library in projects that support ES modules.
2. Improved interoperability: With "type: module" specified, consumers of our library using tools …
> fix: set package type as module

- src/components/radio-group/bl-radio-group.test.ts
- src/components/radio-group/bl-radio-group.ts
This PR fixes `aria-labelledby` definition in radio group component.
> fix(radio): fix aria label

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/feature_request.yml
- .github/ISSUE_TEMPLATE/new-component-definition.yml
Fixes the syntax issues with #585
> docs: update bug_report.yml

- src/components/dialog/bl-dialog.css
- src/components/dialog/bl-dialog.ts
This remove the bottom padding of content area in case of a dialog actions are present. (Outcome of the decision in #600)
@buseselvi If this works for you can you update figma document accordingly?
Fixes #600
> fix(dialog): no bottom padding for content if actions exists

- src/components/button/bl-button.stories.mdx
- src/components/button/bl-button.test.ts
- src/components/button/bl-button.ts
This PR adds `form` property to the button to be able to target an HTML form that is not wrapping the button. I added some documentation as well to explain how to use button with forms as a submitter.
Closes #603
> feat(button): form property added for setting target form

- src/components/input/bl-input.ts
`forceCustomError` and `clearCustomError` methods need to use `validationTarget` property which becomes ready after a full update of the input component. This PR makes sure that those methods wait for finishing the rendering cycle to set/clear custom validation state of the internal input.
Fixes #611
> fix(input): wait for update to set custom error

- src/components/checkbox-group/checkbox/bl-checkbox.css
- src/components/checkbox-group/checkbox/bl-checkbox.test.ts
- src/components/checkbox-group/checkbox/bl-checkbox.ts
> fix(checkbox): remove gap if no label

- src/components/dropdown/group/bl-dropdown-group.test.ts
- src/components/dropdown/group/bl-dropdown-group.ts
`aria-labelledby` definition on `bl-dropdown-group` was wrong. It should have the `id` or an element that contains the label. This PR fixes it.
> fix(dropdown): fix wrong labelledby definition

- src/components/checkbox-group/checkbox/bl-checkbox.test.ts
- src/components/checkbox-group/checkbox/bl-checkbox.ts
The wrong `aria-labelledby` definition was removed since checkbox is already wrapped with a label element.
> fix(checkbox): wrong aria label definition removed

- src/components/dialog/bl-dialog.stories.ts
- src/components/dialog/bl-dialog.test.ts
- src/components/dialog/bl-dialog.ts
A prop has been developed that we can set to use native or polyfill. The fastest solution for managing stacking context in browsers without Popover API. 
Fixes #617
> feat(dialog): add `polyfilled` property for setting native or polyfill

- src/components/tooltip/bl-tooltip.css
- src/components/tooltip/bl-tooltip.test.ts
- src/components/tooltip/bl-tooltip.ts
the top input is the expected state and the bottom is the actual state. (look right gap)
> fix(tooltip): remove extra space

- src/components/radio-group/radio/bl-radio.css
I've noticed an issue with the `bl-radio` component where the radio button's size shrinks if the text within the `#label` element becomes too long. The `#label` element is a flex container, its `:before` pseudo-selector, which is used to create the radio button, is designed with strict width and height settings, leading to this behavior.
The cause of the radio button shrinking is tied to its `flex-shrink` property. However, applying `flex-shrink: 0;` to address this issue would be overly specific.
As a solution, I've implemented a `flex: none;` setting which prevents the radio button from shrinking.
I'm attaching a few example screenshots to illustrate the issue:
> fix(radio): radio button flex-shrink problem

- src/components/input/bl-input.ts
We realized that `bl-invalid` event triggers so many times. This fix avoid this.
Fixes #646
> fix(input): invalid event triggers so many times

- scripts/generate-react-exports.js
This PR adds support to use React components both as value and type.
Example usage:
```tsx
import { BlDialog } from "@trendyol/baklava/dist/baklava-react";
const Component = () => {
const dialogRef = React.useRef<BlDialog>(null);
return (
<BlDialog ref={dialogRef}>...</BlDialog>
)
}
```
Fixes #307
> feat(react): export react component types

- src/components/tooltip/bl-tooltip.css
- src/components/tooltip/bl-tooltip.ts
If you set an input to `width: 100%` and wrap it with the tooltip, you will see that the input shrinks, so we need to set it to `display: flex`.
> feat(tooltip): add css variable for set display of tooltip trigger

- src/components/select/bl-select.stories.mdx
- src/components/select/bl-select.test.ts
- src/components/select/bl-select.ts
This PR fixes the breaking change:
- Select component shouldn't have clear button by default, instead `clearable` attribute should be given to set it clearable
> feat(select): add select clearable prop

- src/components/checkbox-group/checkbox/bl-checkbox.css
Noticed that we are not showing stroke in the Checkbox disabled variant.
Fixes #567
> fix(checkbox): add stroke to checkbox disabled

- src/components/pagination/bl-pagination.stories.mdx
This pull request improves the pagination document by adding an example of itemsPerPageOptions usage.
Fixes: https://github.com/Trendyol/baklava/issues/673
> docs(pagination): adding example of itemsPerPageOptions usage

- docs/design-system/adding-a-new-icon.stories.mdx
- docs/linting.stories.mdx
- src/components/badge/bl-badge.stories.mdx
> docs(storybook): fix some typos in documentation

- src/components/checkbox-group/checkbox/bl-checkbox.css
- src/components/checkbox-group/checkbox/bl-checkbox.stories.mdx
This PR proposes to use `overflow-wrap: anywhere` for checkbox label instead of `word-break: break-all` to provide better readability in case of long texts in small available space.
Fixes #682
Fixes #626
> fix(checkbox): breaking long words better

- src/components/popover/bl-popover.stories.mdx
- src/components/popover/bl-popover.test.ts
- src/components/popover/bl-popover.ts
This PR will allow users to nest popovers inside of each other. Current implementation doesn't allow the use of `bl-tooltip` inside a popover since `bl-tooltip` also uses popover component. 
Closes #703
> feat(popover): allow nested popovers

- src/components/input/bl-input.ts
This PR updates input with every attr/prop changes. So validation can be retriggered in case of validation rule changes, without updating the value.
Fixes #704
> fix(input): revalidate input on prop changes

- scripts/generate-react-exports.js
* Revert back the lazy loading from #709 
* Separate event types for better DX
> chore(react): improve react event types & revert lazy loading

- scripts/generate-react-exports.js
This is a hotfix for recent generate react scripts change, adds back the forgotten React.lazy. 
Before this change Baklava doesn't work with React 16.
> fix(react): wrap with React.lazy

- scripts/generate-react-exports.js
After looking into the discussion at [#716](https://github.com/Trendyol/baklava/pull/716#discussion_r1340999782), I've noticed that we don't need to set the type manually as it's inferred from **React.lazy**. This will give us accurate type of the component and avoid mismatch.
Additionally it fixes appending `undefined` for JSDoc to the `baklava-react.ts`.
> chore(react): infer component types

- src/components/select/bl-select.ts
Some of the attributes that we use for styling were not reflected. I fixed them.
Fixes #719
> fix(select): reflection added for proper styling

- docs/using-baklava-in-vue.stories.mdx
- package.json
- scripts/generate-vue-types.js
This PR brings official TypeScript declerations support for projects with Vue 2.7 and above.
Added docs to storybook.
Output:
```ts
import type * as Baklava from '@trendyol/baklava/dist/baklava'
declare module 'vue' {
export interface GlobalComponents {
BlAlert: import("vue").Component<Baklava.BlAlert>
BlBadge: import("vue").Component<Baklava.BlBadge>
BlButton: import("vue").Component<Baklava.BlButton>
BlCheckboxGroup: import("vue").Component<Baklava.BlCheckboxGroup>
BlDialog: import("vue").Component<Baklava.BlDialog>
BlDrawer: import("vue").Component<Baklava.BlDrawer>
BlDropdown: import("vue").Component<Baklava.BlDropdown>
BlIcon: import("vue").Component<Baklava.BlIcon>
BlInput: import("vue").Component<Baklava.BlInput>
BlPagination: import("vue").Component<Baklava.BlPagination> …
```
> chore(vue): add vue typescript support

- src/components/select/bl-select.ts
Fixes select causing the window to be frozen on choosing x amount of options. This is caused by running `_checkAdditionalItemCount` within updated for each update instead of listening for selected options only.
> fix(select): select check additional count event loop

- src/components/select/bl-select.css
- src/components/select/bl-select.stories.mdx
- src/components/select/bl-select.test.ts
- src/components/select/bl-select.ts
> feat(select): implement select all

- src/components/select/bl-select.css
- src/components/select/bl-select.stories.mdx
- src/components/select/bl-select.test.ts
- src/components/select/bl-select.ts
> fix(select): change select all default behaviour to off

- docs/design-system/colors.stories.mdx
- src/components/alert/bl-alert.css
- src/components/alert/bl-alert.ts
- src/components/notification/card/bl-notification-card.css
- src/components/tooltip/bl-tooltip.css
- src/themes/default.css
Implement new color: Info.
Uptadate alert and notification components info variant color with the new color and update radius to match design document. 
Also update tooltip component default background color to info. This change can be overridden by `--bl-popover-background-color` variable.
Closes #685
> feat: add info color and implement it on alert and notification

- src/components/select/bl-select.stories.mdx
- src/components/select/bl-select.test.ts
- src/components/select/bl-select.ts
- src/components/select/option/bl-select-option.ts
> fix(select): label property added to bl-select-option to fix #764

- docs/using-baklava-in-vue.stories.mdx
In the using-baklava-in-vue.stories.mdx docs the "@ alias" part can be skipped/removed
And added a missing curly brace to make it valid syntax.
> docs(using-baklava-in-vue.stories): 2 small improvements

- src/components/select/bl-select.css
- src/components/select/bl-select.test.ts
- src/components/select/bl-select.ts
Fixes #793 #792 
- Address issue where the popover opens when key downs are triggered while the select is disabled.
- Resolve the inability to set view-select-all to false.
- Fix the issue where the popover opens when search icon clicked.
- Fix the issue the wrong color of item count while the select is disabled.
> fix(select): fix the issue where the popover for a disabled select can still open using keydown events

- src/components/select/bl-select.test.ts
- src/components/select/bl-select.ts
> fix(select): do not show popover if there are no options

- .storybook/preview.ts
- README.md
- docs/welcome.stories.mdx
In this pr, I want to add custom toolbar button in storybook to redirect beta/stable version
> docs(storybook): add version button in storybook toolbar

- src/components/dialog/bl-dialog.test.ts
- src/components/dialog/bl-dialog.ts
This PR removes box-shadow from the footer when scrolling to the end of the content.
Closes #624
> fix(dialog): remove shadow from footer when scroll hits bottom

- src/components/select/bl-select.test.ts
- src/components/select/bl-select.ts
This PR fixes the problem of non-valued options appearing selected in select component.
Closes #625
> fix(select): fix select value bug when undefined

- src/components/select/bl-select.stories.mdx
- src/components/select/bl-select.ts
It was always displaying search placeholder.
Added new stories to the select component in the storybook with label and fixed label options.
Fixes #828
> fix(select): shouln't hide label on searchable

- .github/CODEOWNERS
This will auto assign team as reviewer to newly created PRs
> docs(github): create codeowners

- src/components/select/bl-select.test.ts
- src/components/select/bl-select.ts
Keydown is triggered before input,
causing the select keydown handler to run first.
Fixes #802
> fix(select): fix recurring space closing select box issue

- src/components/dialog/bl-dialog.test.ts
- src/components/dialog/bl-dialog.ts
This PR fixes the propagation issue during close in nested dialogs
Closes #342
> fix(dialog): fix nested dialog propagation problem

- src/components/select/bl-select.stories.mdx
- src/components/select/bl-select.test.ts
- src/components/select/bl-select.ts
This PR allows users to easily access target option based on their keyboard input.
Closes [#686](https://github.com/Trendyol/baklava/issues/686)
> feat(select): improve option navigation by key

- src/components/dialog/bl-dialog.mdx
- src/components/dialog/bl-dialog.stories.ts
- src/components/dialog/bl-dialog.test.ts
- src/components/dialog/bl-dialog.ts
Related to #853
Implements critical dialog functionality to prevent closing and hides the close button for critical dialogs.
- Adds a `critical` property to `bl-dialog` to mark dialogs as critical, which disables closing through keyboard, backdrop, and close button interactions.
- Conditionally renders the close button in the dialog header based on the `critical` property, effectively hiding it for critical dialogs.
- Updates event handling to prevent closing critical dialogs through escape key presses and outside clicks.
- Includes a new story in `bl-dialog.stories.ts` to demonstrate a critical dialog with the `critical` property set to `true`.
- Adds tests in `bl-dialog.test.ts` to verify that critical dialogs cannot be closed through keyboard, backdrop, and close button interactions, …
> feat(dialog): implement critical variant

- src/components/split-button/bl-split-button.ts
closes #867 
we want to try prevent event bubbling for bl-buttons inside bl-split-button. @hakanbytunc
> fix(split-button): fix event bubbling for buttons inside split button

- docs/using-baklava-in-next.stories.mdx
Baklava needs to be imported as a module. Next <Script> does not take "type" as a parameter so lowercase <script> should be used.
I am creating a new Next project with Baklava and this solved my issue.
> fix: Use lowercase script import in using-baklava-in-next.stories.mdx

- src/baklava.ts
- src/components/button/bl-button.css
- src/components/button/bl-button.stories.mdx
- src/components/button/bl-button.test.ts
- src/components/button/bl-button.ts
- src/components/input/bl-input.stories.mdx
- src/components/input/bl-input.test.ts
- src/components/input/bl-input.ts
- src/components/select/bl-select.css
- src/components/select/bl-select.test.ts
- src/components/select/bl-select.ts
- src/components/spinner/bl-spinner.css
- src/components/spinner/bl-spinner.stories.mdx
- src/components/spinner/bl-spinner.test.ts
- src/components/spinner/bl-spinner.ts
> feat: spinner component

- src/components/input/bl-input.stories.mdx
- src/components/input/bl-input.test.ts
- src/components/input/bl-input.ts
This PR allows preventing `Enter` from submitting the parent form. 
Closes #676
> feat(input): prevent enter to submit form

- src/components/checkbox-group/checkbox/bl-checkbox.stories.mdx
- src/components/checkbox-group/checkbox/bl-checkbox.ts
> fix(checkbox): fix validation state of checkbox

- src/components/dialog/bl-dialog.css
- src/components/dialog/bl-dialog.mdx
- src/components/dialog/bl-dialog.stories.ts
- src/components/dialog/bl-dialog.test.ts
- src/components/dialog/bl-dialog.ts
Added the --bl-dialog-width and --bl-dialog-caption-line-clamp CSS properties.
Closes #737
> feat(dialog): add width and caption line clamp css property

- src/components/tooltip/bl-tooltip.ts
closes #908 
I noticed there is a problem when we use `mouseover` as event listener in bl-tooltip component. mouseever triggered for every children inside tooltip trigger slot. It should be triggered only once when mouse entered the tooltip trigger slot element instead of its children. If we use `mouseenter` as event listener it seems problem solved.
I put the video about this case also:
https://github.com/user-attachments/assets/a7b4ea3b-8c5a-47e9-9dbc-69a62da5d7d1
> fix(tooltip): use mouseenter as event listener

- playground/template.html
- src/components/input/bl-input.stories.mdx
- src/components/input/bl-input.test.ts
- src/components/input/bl-input.ts
- src/components/textarea/bl-textarea.stories.mdx
- src/components/textarea/bl-textarea.test.ts
- src/components/textarea/bl-textarea.ts
- src/generated/locales/tr.ts
- src/utilities/form-control.test.ts
- src/utilities/form-control.ts
- translations/tr.xlf
customInvalidText, forceCustomError and clearCustomError are deprecated
add error attribute
> refactor: improve form validation

- src/components/dropdown/bl-dropdown.stories.mdx
- src/components/dropdown/bl-dropdown.test.ts
- src/components/dropdown/item/bl-dropdown-item.stories.mdx
- src/components/dropdown/item/bl-dropdown-item.test.ts
- src/components/dropdown/item/bl-dropdown-item.ts
- src/components/split-button/bl-split-button.test.ts
Also use the appropriate custom event to ensure that the feature set works as intended.
Closes #1017
> feat(dropdown): add support for disabling dropdown items
