Trendyol/baklava

- README.md
This pull request fix wrong issue url in the readme.md file.
> fix wrong issue url

- src/components/GButtonDropdown/GButtonDropdown.vue
> bind attrs to GButtonDropDown

- package.json
> Update npm version to 1.0.17

- package.json
- src/components/GInputPrice/GInputPrice.vue
added allowMinus attr to computed
> feature/GInputPrice-allowMinus, added allowMinus attr

- package-lock.json
- package.json
- src/components/GSelect/GSelect.spec.ts
- src/components/GSelect/GSelect.stories.ts
- src/components/GSelect/GSelect.vue
- src/components/GSelect/__snapshots__/GSelect.spec.ts.snap
- I should not need to map a specific array.
- Implement `valueKey`, `textKey` props for dynamic value and text keys similar to GNativeSelect.
- I should be able to get back the selected object on input event.
- Implement `reduceValue` prop.
> GSelect dynamic keys and reduce value props

- .storybook/main.js
- CONTRIBUTING.md
- README.md
- docs/contributing.stories.mdx
> docs: readme and contributing docs are created

- .github/workflows/verify.yml
- .storybook/main.js
**iframe.html** and **index.html** files in **storybook-static** folder (generated with `build-storybook`) contain `<title>Webpack App</title>` as default.
Added **webpackFinal** (for iframe.html) and **managerWebpack** (for index.html) into **.storybook/main.js** to override **HtmlWebpackPlugin**'s `title` option.
> feat(storybook): updated html title

- .gitignore
- .vscode/extensions.json
Related to #189. 
This PR currently adds plugins below as suggested ones for VSCode;
- [Eslint](https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint),
- [lit-plugin](https://marketplace.visualstudio.com/items?itemName=runem.lit-plugin), 
- [EditorConfig for VS Code](https://marketplace.visualstudio.com/items?itemName=EditorConfig.EditorConfig), 
- [MDX](https://marketplace.visualstudio.com/items?itemName=silvenon.mdx)
// suggested by @leventozen 
- [code-spell-checker](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker)
- [prettier](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode)
- [stylelint](https://marketplace.visualstudio.com/items?itemName=stylelint.vscode-stylelint)
> chore: added vscode recommended extensions (#189)

- docs/design-system/border-radius.stories.mdx
- src/components/tab-group/bl-tab-group.css
- src/components/tab-group/tab-panel/bl-tab-panel.css
- src/themes/default.css
Border radius variables are defined to root css and changed static variables.
Closes #185
> chore: describe border radius variables

- docs/design-system/border-radius.stories.mdx
Fixes border radius variable on design system docs.
> docs: fix border radius rem variable

- LICENSE
I noticed we removed the license file while we created this version from the previous (grace).
> chore: create license file

- src/components/button/bl-button.css
- src/components/input/bl-input.css
This pr includes two changes:
1.  Add new hover background color variable for text button and delete text-decoration:underline 
2. Fix linting problem of bl-input.css
> feat(button): refactor hover state for text button

- docs/design-system/sizing.stories.mdx
This pl includes a sizing doc:
- To show the sizing variables in baklava with their values and,
- To illustrate the usage
> docs(design): add sizing to design system

- docs/customizing-baklava-theme.stories.mdx
- docs/how-to-customize-a-components-style.stories.mdx
This document adds information about how we use design token variables and how to customize them.
Closes #231
> docs: theme customization document added

- CODE_OF_CONDUCT.md
I used the tool of GitHub to create this document. As our community grows, applying that kinds of rules to our project would be helpful.
> chore: generic code of conduct document added

- src/components/progress-indicator/bl-progress-indicator.ts
Reflection is added for properties that are used as CSS selectors in the component.
Fixes #295
> fix(progress-indicator): add reflect for props

- commitlint.config.js
- docs/using-baklava-in-react.stories.mdx
- src/baklava.ts
- src/components/dialog/bl-dialog.css
- src/components/dialog/bl-dialog.stories.mdx
- src/components/dialog/bl-dialog.test.ts
- src/components/dialog/bl-dialog.ts
The attributes,events and the general usage of the dialog are mentioned in:
Closes https://github.com/Trendyol/baklava/issues/137
> feat: dialog component

- README.md
- src/themes/default.css
Includes: 
* Removing FOUCE effect style,
* Adding FOUCE effect warning to docs.
Closes #344.
> fix: remove fouce effect styles from default theme

- src/components/button/bl-button.css
- src/components/button/bl-button.ts
- src/components/pagination/bl-pagination.css
See the button centering bug on:
https://trendyol.github.io/baklava/?path=/docs/components-button--button-sizes
Includes: 
* bl-button 'justify-content' variable fix, documentation update,
* bl-pagination color fix.
> fix(button): fix css variable typo

- src/components/input/bl-input.test.ts
- src/components/input/bl-input.ts
Some accessibility improvements for our input components.
Closes #294
> fix(input): a11y improvements

- src/components/tooltip/bl-tooltip.css
- src/components/tooltip/bl-tooltip.test.ts
- src/components/tooltip/bl-tooltip.ts
This PR fixes some issues on Tooltip component.
* Positioning on scroll (#311)
* Clipping in small screens (#310)
* Accessibility improvements (#286)
Fixes #311, fixes #310 and closes #286
> fix(tooltip): a11y and UI consistency improvements

- src/components/tab-group/bl-tab-group.test.ts
- src/components/tab-group/bl-tab-group.ts
- src/components/tab-group/tab/bl-tab.test.ts
- src/components/tab-group/tab/bl-tab.ts
> fix(tab): tracking selected attribute for each tab

- commitlint.config.js
- src/baklava.ts
- src/components/switch/bl-switch.css
- src/components/switch/bl-switch.stories.mdx
- src/components/switch/bl-switch.test.ts
- src/components/switch/bl-switch.ts
> feat: switch component

- src/components/drawer/bl-drawer.css
- src/components/drawer/bl-drawer.ts
I noticed that our drawer component is not working well in iOS Safari, aligning with notch (or dynamic island) and bottom bar.  I propose a set of fixes for that kind of issues.
| Before | After |
| ------ | -- |
| ![Simulator Screen Shot - iPhone 14 Pro - 2023-01-21 at 22 42 51](https://user-images.githubusercontent.com/127687/213888187-e2eec469-b3fc-43eb-8e78-a3b2a1428f9a.png) | ![Simulator Screen Shot - iPhone 14 Pro - 2023-01-21 at 22 42 15](https://user-images.githubusercontent.com/127687/213888195-c0052fa7-0421-43d7-af5b-86cf3269b734.png) |
| ![Simulator Screen Shot - iPhone 14 Pro - 2023-01-21 at 22 43 06](https://user-images.githubusercontent.com/127687/213888156-6ca54866-f75e-4f4b-a46a-ba033c49371a.png) | ![Simulator Screen Shot - iPhone 14 Pro - 2023-01-21 at 22 41 …
> fix(drawer): visual fixes for viewport safe margins

- src/components/button/bl-button.css
> fix(button): designs for focused state

- src/components/pagination/bl-pagination.css
- src/components/pagination/bl-pagination.test.ts
- src/components/pagination/bl-pagination.ts
> fix(pagination): accessibility improvements

- package-lock.json
- package.json
- src/components/drawer/bl-drawer.test.ts
- src/components/textarea/bl-textarea.test.ts
- src/components/textarea/bl-textarea.ts
- src/utilities/form-control.ts
I updated form participation and element internal polyfill dependencies.
This fixes an issue about `BlButton` as a submit button in a form in React.
I also fixed a few issues in Drawer component tests those causes lots of logs while running tests.
> fix: form participation fixes

- src/components/textarea/bl-textarea.test.ts
Simplified one test case that fails very often with timeout error
Fixes #413
> test(textarea): testing simplified to running it quicker

- package-lock.json
- package.json
> chore: update lit

- package.json
- src/components/button/bl-button.stories.mdx
> docs: add homepage field to package.json

- .storybook/preview-body.html
- src/components/select/bl-select.stories.mdx
We started to run cross-browser snapshot tests on Chromatic and we realised that one of the stories of Select components doesn't work in Firefox. This PR fixes the issue, as well as making that story easier to test manually (by adding a submit button).
> docs(select): better form validation demo

- .storybook/main.ts
@MehmetFiratKomurcu warned me that I missed some commented and unneeded code block in storybook configuration in my last PR (#522). This PR cleans them.
Thank you @MehmetFiratKomurcu 😊
> refactor(storybook): clean unneeded code

- src/components/tab-group/bl-tab-group.css
> fix(tab): fix the persistent scrollbar issue for the tab-group component

- .storybook/preview-body.html
- package-lock.json
- package.json
- src/themes/default.css
This PR upgrades the version of our rubik font source. New version introduces [customizing `font-style` via CSS variable](https://github.com/fontsource/fontsource/issues/121).
> chore(deps): rubik font version upgrade

- docs/customizing-baklava-theme.stories.mdx
> docs: fixed typo in customizing-baklava-theme file  fixes #638

- src/components/input/bl-input.css
- src/components/input/bl-input.ts
> feat(input): set padding-horizontal values with css properties

- src/components/input/bl-input.css
- src/components/input/bl-input.stories.mdx
- src/components/input/bl-input.test.ts
- src/components/input/bl-input.ts
> Implement Icon slot for bl-input

- src/components/input/bl-input.stories.mdx
- src/components/input/bl-input.ts
Added support for following input types
* email
* time
* datetime-local
* month
* week
> feat(input): support more input types

- CONTRIBUTING.md
This PR addresses various grammatical errors and enhances clarity in the contribution guidelines for the Baklava Design System documentation. The changes aim to improve readability and ensure accurate communication of the contribution process. Below is a summary of the modifications made:
- Fixed typos and grammatical errors throughout the document.
- Clarified sentence structures for better understanding.
- Provided more precise instructions for contributors to follow.
> docs: Fixed grammar mistakes in contributing docs

- src/utilities/asset-paths.ts
I believe it could be healthier and more readable this way.
What do you think?
> refactor: default iconPath

- src/components/select/bl-select.ts
Bug fix for https://github.com/Trendyol/baklava/issues/816 issue
> fix(select): fix divider displaying for single variant

- commitlint.config.cjs
- src/baklava.ts
- src/components/dropdown/item/bl-dropdown-item.ts
- src/components/split-button/bl-split-button.css
- src/components/split-button/bl-split-button.stories.mdx
- src/components/split-button/bl-split-button.test.ts
- src/components/split-button/bl-split-button.ts
Split button component completed.
Closes #264
> feat: split-button component

- src/components/select/bl-select.css
- src/components/select/bl-select.test.ts
- src/components/select/bl-select.ts
> fix(select): removing popover element from dom causes error on popover setup

- src/components/checkbox-group/bl-checkbox-group.css
- src/components/checkbox-group/bl-checkbox-group.stories.mdx
- src/components/checkbox-group/bl-checkbox-group.test.ts
- src/components/checkbox-group/bl-checkbox-group.ts
- src/components/checkbox-group/checkbox/bl-checkbox.css
- src/components/checkbox-group/checkbox/bl-checkbox.stories.mdx
- src/components/checkbox-group/checkbox/bl-checkbox.test.ts
- src/components/checkbox-group/checkbox/bl-checkbox.ts
> fix(checkbox): fix error state of checkbox/ checkbox group

- src/components/popover/bl-popover.ts
- src/components/tooltip/bl-tooltip.stories.mdx
- src/components/tooltip/bl-tooltip.test.ts
- src/components/tooltip/bl-tooltip.ts
- src/utilities/elements.ts
> feat(tooltip): add target attribute

- .github/dependabot.yml
> chore: update dependabot.yml configuration

- src/components/select/bl-select.ts
- src/localization.ts
> feat(select): Improve select search international character support

- src/components/select/bl-select.ts
fix search text is not clear bug when user click clear button 
case: single select / clearable
closes #845
> feat(select): fix search text is not clear bug when user click clear button

- src/components/dialog/bl-dialog.css
- src/components/dialog/bl-dialog.mdx
- src/components/dialog/bl-dialog.stories.ts
> style(dialog): tab-group inside dialog

- src/components/checkbox-group/checkbox/bl-checkbox.css
- src/components/checkbox-group/checkbox/bl-checkbox.test.ts
- src/components/checkbox-group/checkbox/bl-checkbox.ts
> fix(checkbox): add relative value for position in checkbox container

- src/components/table/bl-table.stories.mdx
- src/components/table/bl-table.test.ts
- src/components/table/bl-table.ts
- src/components/table/table-row/bl-table-row.ts
Otherwise it removes previous selections on paginated table. 
Closes #910.
> fix(table): multiple checkbox should only handle currently rendered rows

- src/components/icon/bl-icon.ts
- src/components/input/bl-input.test.ts
- src/components/input/bl-input.ts
improves type safety for
* input
* icon
> chore(input): improve type-safety

- src/components/input/bl-input.css
- src/components/input/bl-input.test.ts
- src/components/input/bl-input.ts
This PR addresses and resolves issue https://github.com/Trendyol/baklava/issues/715.
> feat(input): add clear button for search input (#715)

- src/components/popover/bl-popover.ts
This pr resolves https://github.com/Trendyol/baklava/issues/1010
> #1010 update bl-popover for event bubbling

- src/components/button/bl-button.css
- src/components/datepicker/bl-datepicker.stories.mdx
- src/components/tag/bl-tag.stories.mdx
- src/components/tag/bl-tag.ts
- src/components/tag/doc/ADR.md
* fixes icon button by adding min-width
* fix tag adr
> fix(button): button min-width

- src/components/input/bl-input.stories.mdx
- src/components/input/bl-input.test.ts
- src/components/input/bl-input.ts
> fix(input): trigger input event on clear

- src/components/dialog/bl-dialog.css
- src/components/dialog/bl-dialog.test.ts
- src/components/dialog/bl-dialog.ts
Dialog was only showing footer depending on whether bl-button is present or not. Also, since slot is uncontrolled, it can show footer as false positive.
Closes #1004
> fix(dialog): improve footer visibility
